import {
  GitBranch,
  Link,
  X,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Code,
  Layout,
  Terminal,
  Rocket,
  Star,
  Heart,
  ArrowRight,
  Menu,
  X as XIcon,
  Sun,
  Moon,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Filter,
  Download,
  ExternalLink,
  Copy,
  Check,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Loader,
  RefreshCw,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  Settings,
  User,
  Users,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Image,
  Video,
  Music,
  FileText,
  Folder,
  FolderOpen,
  Tag,
  Tags,
  Bookmark,
  Share2,
  Briefcase,
  GraduationCap,
} from "lucide-react";

export const Icons = {
  github: GitBranch,
  linkedin: Link,
  x: X,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  calendar: Calendar,
  code: Code,
  design: Layout,
  terminal: Terminal,
  rocket: Rocket,
  star: Star,
  heart: Heart,
  arrowRight: ArrowRight,
  menu: Menu,
  close: XIcon,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  filter: Filter,
  download: Download,
  externalLink: ExternalLink,
  link: Link,
  copy: Copy,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertTriangle: AlertTriangle,
  loader: Loader,
  refreshCw: RefreshCw,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash2: Trash2,
  save: Save,
  settings: Settings,
  user: User,
  users: Users,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  image: Image,
  video: Video,
  music: Music,
  fileText: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  tag: Tag,
  tags: Tags,
  bookmark: Bookmark,
  share2: Share2,
  briefcase: Briefcase,
  graduationCap: GraduationCap,
} as const;

export type IconName = keyof typeof Icons;